#! /bin/sh

bspc config border_width                1
bspc config window_gap					23
bspc config split_ratio                 0.50
bspc config left_padding				0
bspc config right_padding				0
bspc config bottom_padding				0
bspc config top_padding 				15
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       false
bspc config auto_alternate              false
bspc config auto_cancel                 true
bspc config top_padding                 24
bspc config normal_border_color         "#181512"
bspc config focused_border_color        "#A9A2A2"
bspc config presel_border_color         "#AC4142"

bspc config click_to_focus				true
bspc config pointer_modifier			super

bspc config normal_frame_opacity        0.0
bspc config focused_frame_opacity       0.05

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc rule -a Gimp desktop=^8 follow=on state=floating
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating manage=off
bspc rule -a dolphin state=floating
bspc rule -a pidgin desktop=^9 follow=on state=floating
bspc rule -a Steam floating=on
bspc rule -a Unity state=floating
bspc rule -a "TeamViewer.exe" state=floating
bspc rule -a "TeamViewer" state=floating
bspc rule -a "soffice" state=floating
bspc rule -a thunar state=floating
bspc rule -a skypeforlinux state=floating
bspc rule -a wire state=floating
bspc rule -a Wire state=floating
bspc rule -a qemu-system-i38 state=floating
bspc config external_rules_command "$(which external_rules)"
bspc config rule_command "$(which rule_command)"

#bspwm_rules

$HOME/.config/bspwm/init.sh &
$HOME/.config/bspwm/rules.sh &
PANEL_FIFO="/tmp/fifo" panel &
